### ISSUE TITLE
updating to 1.3.5 and creating a new camera gives error

### ISSUE THREAD

**Issue by blysik** [bkmar1192/SecurityCamera#2]
I updated to 1.3.5, and now when I create a new camera I get this error:

Traceback (most recent call last):
  File "plugin.py", line 465, in runConcurrentThread
KeyError: 'key CameraUserName not found in dict'

   Security Camera Error           plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

I notice that now there's a single line for the camera url, so I'm putting <user>:<pass>@ip/path

**Comment by blysik** [comment]
Your README says "a dialog will pop up that will guide you through creating the url".  But that doesn't happen for me at all.

**Comment by bkmar1192** [comment]
I'll upload a fix for the CameraUserName issue shortly.

I edited the README to make it more clear.  That was in reference to the iSpy web site and not to the plugin itself.
